INSERT INTO STUDENT (first_name, last_name, email) VALUES
  ('Lokesh', 'Gupta', 'abc@gmail.com'),
  ('Deja', 'Vu', 'xyz@email.com'),
  ('Juan', 'Perez-Cruz', 'juan.perez-cruz@perezcruzvinos.cl'),
  ('Ivan', 'Araya', 'ivan.araya.t@email.com'),
  ('Daniel', 'Barraza', 'dbarrazac@gmail.com'),
  ('Tom', 'Araya', 'tomas.araya@slayer.com'),
  ('Orlando', 'Sepúlveda', 'ojsepu@gmail.com'),
  ('Francisco', 'González-Zeballos', 'fgonzalezz@gmail.com'),
  ('Pablo', 'Parra', 'parra.pablo.r@mail.com'),
  ('Alejandro', 'Barahona', 'abarahona@visiion.cl'),
  ('Jorge Alberto', 'Serra Possetto', 'aserra@visiionmail.com'),
  ('Rodrigo', 'Olivos', 'rolivos@email.com'),
  ('Enzo', 'Serra', 'eserra@email.com'),
  ('Antonio', 'Matras', 'amatras@email.com'),
  ('Hernando', 'De Magallanes', 'hm@email.com'),
  ('Pedro', 'De Valdivia', 'pdv@email.com'),
  ('Manuel', 'Montt', 'm.montt@marvel.com'),
  ('Caption', 'America', 'cap@marvel.com'),
  ('Lokesh', 'Gupta', 'abc@gmail.com'),
  ('Deja', 'Vu', 'xyz@email.com'),
  ('Juan', 'Perez-Cruz', 'juan.perez-cruz@perezcruzvinos.cl'),
  ('Ivan', 'Araya', 'ivan.araya.t@email.com'),
  ('Daniel', 'Barraza', 'dbarrazac@gmail.com'),
  ('Tom', 'Araya', 'tomas.araya@slayer.com'),
  ('Orlando', 'Sepúlveda', 'ojsepu@gmail.com'),
  ('Francisco', 'González-Zeballos', 'fgonzalezz@gmail.com'),
  ('Pablo', 'Parra', 'parra.pablo.r@mail.com'),
  ('Alejandro', 'Barahona', 'abarahona@visiion.cl'),
  ('Jorge Alberto', 'Serra Possetto', 'aserra@visiionmail.com'),
  ('Rodrigo', 'Olivos', 'rolivos@email.com'),
  ('Enzo', 'Serra', 'eserra@email.com'),
  ('Antonio', 'Matras', 'amatras@email.com'),
  ('Hernando', 'De Magallanes', 'hm@email.com'),
  ('Pedro', 'De Valdivia', 'pdv@email.com'),
  ('Manuel', 'Montt', 'm.montt@marvel.com'),
  ('Caption', 'America', 'cap@marvel.com');