INSERT INTO STUDENT (firstname, lastname, email) VALUES
  ('Lokesh', 'Gupta', 'abc@gmail.com'),
  ('Deja', 'Vu', 'xyz@email.com'),
  ('Juan', 'Perez-Cruz', 'juan.perez-cruz@perezcruzvinos.cl'),
  ('Ivan', 'Araya', 'ivan.araya.t@email.com'),
  ('Daniel', 'Barraza', 'dbarrazac@gmail.com'),
  ('Tom', 'Araya', 'tomas.araya@slayer.com'),
  ('Orlando', 'Sepúlveda', 'ojsepu@gmail.com'),
  ('Francisco', 'González-Ceballos', 'fgonzalezc@gmail.com'),
  ('Pablo', 'Parra', 'parra.pablo.r@mail.com'),
  ('Alejandro', 'Barahona', 'abarahona@vision.co.cl'),
  ('Jorge Alberto', 'Sierra Poscietti', 'asierra@visionmail.com'),
  ('Rodrigo', 'Olivos', 'rolivos@email.com'),
  ('Enzo', 'Sierra', 'esierra@email.com'),
  ('Antonio', 'Matras', 'amatras@email.com'),
  ('Hernando', 'De Magallanes', 'hm@email.com'),
  ('Pedro', 'De Valdivia', 'pdv@email.com'),
  ('Manuel', 'Montt', 'm.montt@marvel.com'),
  ('Caption', 'America', 'cap@marvel.com'),
  ('Lokesh', 'Gupta', 'abc@gmail.com'),
  ('Deja', 'Vu', 'xyz@email.com'),
  ('Juan', 'Perez-Cruz', 'juan.perez-cruz@perezcruzvinos.cl'),
  ('Ivan', 'Araya', 'ivan.araya.t@email.com'),
  ('Daniel', 'Barraza', 'dbarrazac@gmail.com'),
  ('Tom', 'Araya', 'tomas.araya@slayer.com'),
  ('Orlando', 'Sepúlveda', 'ojsepu@gmail.com'),
  ('Francisco', 'González-Ceballos', 'fgonzalezc@gmail.com'),
  ('Pablo', 'Parra', 'parra.pablo.r@mail.com'),
  ('Alejandro', 'Barahona', 'abarahona@visionmail.com.au'),
  ('Jorge Alberto', 'Sierra Poscietti', 'asierra@visionmail.com.ar'),
  ('Rodrigo', 'Olivos', 'rolivos@email.com'),
  ('Enzo', 'Sierra', 'esierra@email.com'),
  ('Antonio', 'Matras', 'amatras@email.com'),
  ('Hernando', 'De Magallanes', 'hm@email.com'),
  ('Pedro', 'De Valdivia', 'pdv@email.com'),
  ('Manuel', 'Montt', 'm.montt@marvel.com'),
  ('Caption', 'America', 'cap@marvel.com');